/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.final_plproject;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author The First
 */
 public class ViewPenaltiesJframe extends javax.swing.JFrame {
    
    // INSERT THESE HERE
    private java.io.File penaltiesFile = new java.io.File("C:\\Users\\The First\\Downloads\\pl-project-d40f7c64096cf702fd2763bde563f9559bfd9fe0\\pl-project-d40f7c64096cf702fd2763bde563f9559bfd9fe0\\Final_PlProject\\text files\\penalties.txt"); 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ViewPenaltiesJframe.class.getName());
    
    private int getUserID() {
        // This should return the ID of the logged-in user
        return 1; 
    }
    /**
     * Creates new form ViewPenaltiesJframe
     */
    public ViewPenaltiesJframe() {
        initComponents();
        loadPenaltiesToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("View Penalties");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 15, 210, 40));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "DATE", "REASON", "AMOUNT"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 380, 140));

        jButton1.setBackground(new java.awt.Color(153, 0, 51));
        jButton1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("logout");
        jButton1.setActionCommand("");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 120, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\The First\\Downloads\\pl-project-d40f7c64096cf702fd2763bde563f9559bfd9fe0\\pl-project-d40f7c64096cf702fd2763bde563f9559bfd9fe0\\Final_PlProject\\src\\main\\java\\com\\images\\bluee3.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 400, 310));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      this.dispose();  
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ViewPenaltiesJframe().setVisible(true));}
        
    private void loadPenaltiesToTable() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Clear the table first
   if (penaltiesFile.isDirectory()) {
        System.out.println("ERROR: Your path points to a FOLDER. It must point to the FILE.");
        return;
    }
    try (java.util.Scanner scanner = new java.util.Scanner(penaltiesFile)) {
        System.out.println("File opened successfully. Reading lines...");
        while (scanner.hasNextLine()) { 
            String line = scanner.nextLine();
            if (line.trim().isEmpty()) continue;
            String[] data = line.split(",");

            // Logic from your function: check length and UserID
            if (data.length >= 4 && data[1].equals(String.valueOf(getUserID()))) {
                // data[2] = Date, data[3] = Reason
                // We add them as a new row in the UI table
                model.addRow(new Object[]{data[2], data[3], "Check File"}); 
            }
        }
    } catch (java.io.FileNotFoundException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error: penalties.txt not found!");
    }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
